from .calculate_ratings_rank_correlation import RatingsCorrelationTask
from .correlation_count_of_marks_and_count_of_comments import MarksAndCommentsCountsCorrelation
from .correlation_date_litres_and_date_writing import DatesCorrelationTask
from .count_books_by_year_on_litres import CountingByLitresDateTask
